version: "3"

services:
  app:
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./app:/opt:z
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dporto/nas:/datanas
      - /mnt/nas:/mnt/nas
      - ./install_apps.sh:/src/install_apps.sh
      - /workspace:/workspace
  samba:
    image: dperson/samba
    environment:
      - USERID=1097
      - GROUPID=1145
    ports:
      - 139:139
      - 445:445
    # https://hub.docker.com/r/dperson/samba
    command:  -u "dporto;kaioken;" -s "devel;/data;yes;no;no;dporto"
    volumes:
      - ./data:/data
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    environment:
      - APP_USERNAME=harvey
      - APP_PASSWORD_HASH=JDJhJDEwJEVKM0FhUTJvdkdIb2VZdkE0WVhMWS5WMFlkSW5TZTAuL0R4Z3NYdGx1NmgxdmVVVUhUMUhh
      # compute the password with docker run --rm -it gitkraken-remote_caddy caddy hash-password -plaintext 'aaa'
      # aaa : JDJhJDEwJEVKM0FhUTJvdkdIb2VZdkE0WVhMWS5WMFlkSW5TZTAuL0R4Z3NYdGx1NmgxdmVVVUhUMUhh
      # - APP_PASSWORD_HASH=JDJhJDEwJEZrSllrdEF5a3F5TjNsU2hXYW1ub2V2TFBWTC5YbTJYeWpIRWI3YW5wMzVlTGRkeURLM2Qu
    volumes:
      - ./data:/data
    ports:
      - 8864:8080


